<a href="https://colab.research.google.com/github/DrSubbiah/6.Python/blob/main/PANDAS_lambdaEg.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

file1 = pd.DataFrame({
    'name': ['alice','bob','charlie','daniel'],
    'age': [25,66,56,78]
})

In [ ]:
file1

      name  age
0    alice   25
1      bob   66
2  charlie   56
3   daniel   78

In [ ]:
file1.assign(
    is_senior = lambda dataframe: dataframe['age'].map(lambda x: "Senior" if x >= 65 else "NonSenior"),
    is_senior1 = lambda dataframe: dataframe['age'].map(lambda x: True if x >= 65 else False)
)

      name  age  is_senior  is_senior1
0    alice   25  NonSenior       False
1      bob   66     Senior        True
2  charlie   56  NonSenior       False
3   daniel   78     Senior        True

In [ ]:
file1.assign(
    is_senior = lambda dataframe: dataframe['age'].map(lambda age: True if age >= 65 else False) ,
    ).assign(
    name_uppercase = lambda dataframe: dataframe['name'].map(lambda name: name.upper()),
    ).assign(
    name_uppercase_double = lambda dataframe: dataframe['name_uppercase'].map(lambda name: name.upper()+"-"+name.upper()))